# Generated by Django 5.1.1 on 2024-09-30 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('funcao_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro.funcaomembro')),
            ],
        ),
    ]
