# Generated by Django 5.1.3 on 2024-11-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadesCulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'atividadesculto',
            },
        ),
        migrations.CreateModel(
            name='RelatorioCulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField(verbose_name='Horário Começo')),
                ('hora_termino', models.TimeField(verbose_name='Horário Fim')),
                ('total_pessoas', models.IntegerField(default=0, verbose_name='Total Geral')),
                ('total_mulheres', models.IntegerField(default=0)),
                ('total_homens', models.IntegerField(default=0)),
                ('total_juniores', models.IntegerField(default=0)),
                ('total_jovens', models.IntegerField(default=0)),
                ('total_visitantes', models.IntegerField(default=0)),
                ('ministro', models.CharField(blank=True, max_length=100, null=True)),
                ('tema', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mensagem/Tema')),
                ('total_dizimos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Total Dízimos')),
                ('total_ofertas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('total_novos_convertidos', models.IntegerField(default=0)),
                ('total_novos_batizandos', models.IntegerField(default=0)),
                ('atividades', models.ManyToManyField(db_table='atividadesrelatorioculto', to='relatorios.atividadesculto')),
                ('culto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.agendasemanal')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.evento')),
            ],
            options={
                'db_table': 'relatorioculto',
            },
        ),
    ]
