# Generated by Django 5.1.1 on 2024-09-30 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicao', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'funcao',
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_ingressao', models.IntegerField(blank=True, null=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicao.instituicaosede')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.usuario')),
            ],
            options={
                'db_table': 'membro',
            },
        ),
        migrations.CreateModel(
            name='FuncaoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro.departamento')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro.funcao')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro.membro')),
            ],
            options={
                'db_table': 'funcaomembro',
            },
        ),
    ]
