# Generated by Django 5.1.1 on 2024-09-30 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('foto', models.CharField(max_length=25)),
                ('celular', models.CharField(max_length=16)),
                ('senha', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=60)),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
