# Generated by Django 5.1.2 on 2024-11-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
                ('uf', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'unidadefederativa',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('rua', models.CharField(max_length=60)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=9)),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadefederativa', verbose_name='Unidade Federativa')),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
    ]
