# Generated by Django 5.1.2 on 2024-11-06 12:06

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ingressao', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'participanteevento',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(max_length=255, upload_to='posts/capa/')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Para que o evento seja considerado gratuito, basta deixar o campo de valor em branco.', max_digits=10, null=True)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco')),
            ],
            options={
                'db_table': 'evento',
            },
        ),
    ]
