# Generated by Django 5.1.3 on 2024-11-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuario.instituicaosede'),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='evento.evento'),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_confirmados', to='usuario.membro'),
        ),
    ]
