# Generated by Django 5.1.1 on 2024-09-30 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicao', '0001_initial'),
        ('membro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoContribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'metodocontribuicao',
            },
        ),
        migrations.CreateModel(
            name='TipoContribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipocontribuicao',
            },
        ),
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro.departamento')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicao.instituicao')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribuicao.metodocontribuicao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribuicao.tipocontribuicao')),
            ],
            options={
                'db_table': 'contribuicao',
            },
        ),
        migrations.CreateModel(
            name='ContatosContribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membro.departamento')),
                ('contribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribuicao.contribuicao')),
            ],
            options={
                'db_table': 'contatoscontribuicao',
            },
        ),
    ]
