# Generated by Django 5.1.2 on 2024-11-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatosContribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('oferta', 'Oferta'), ('dizimo', 'Dízimo'), ('doacao', 'Doação'), ('caridade', 'Campanhas de Caridade'), ('missoes', 'Contribuição para Missões'), ('manutencao_tempo', 'Manutenção do Templo')], max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'contatoscontribuicao',
            },
        ),
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pix', 'Pix'), ('deposito', 'Depósito')], max_length=20, verbose_name='Método da Contribuição')),
                ('tipo', models.CharField(choices=[('oferta', 'Oferta'), ('dizimo', 'Dízimo'), ('doacao', 'Doação'), ('caridade', 'Campanhas de Caridade'), ('missoes', 'Contribuição para Missões'), ('manutencao_tempo', 'Manutenção do Templo')], max_length=50)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contribuicao',
            },
        ),
        migrations.CreateModel(
            name='MetodoContribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'metodocontribuicao',
            },
        ),
        migrations.CreateModel(
            name='TipoContribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipocontribuicao',
            },
        ),
    ]
