# Generated by Django 5.1.1 on 2024-09-30 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('dia_semana', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, max_length=10, null=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicao.instituicao')),
            ],
            options={
                'db_table': 'agendasemanal',
            },
        ),
    ]
