# Generated by Django 5.1.3 on 2024-11-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendasemanal',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_semanais', to='usuario.instituicaosede'),
        ),
        migrations.AddField(
            model_name='agendasemanal',
            name='icone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.iconeagendasemanal'),
        ),
    ]
