# Generated by Django 5.1.2 on 2024-11-06 12:06

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(max_length=255, upload_to='posts/arquivos/')),
            ],
            options={
                'db_table': 'arquivopost',
            },
        ),
        migrations.CreateModel(
            name='CategoriaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoriapost',
            },
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'curtida',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(blank=True, max_length=255, null=True, upload_to='posts/capa/')),
                ('fixado', models.BooleanField(default=False, verbose_name='Deseja fixar esse post?')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', django_ckeditor_5.fields.CKEditor5Field()),
                ('hora', models.TimeField(auto_now=True)),
                ('data', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Salvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'salvo',
            },
        ),
    ]
