# Generated by Django 5.1.3 on 2024-11-09 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curtida',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.categoriapost'),
        ),
        migrations.AddField(
            model_name='post',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='usuario.instituicaosede'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curtida',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtida', to='posts.post'),
        ),
        migrations.AddField(
            model_name='arquivopost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='posts.post'),
        ),
        migrations.AddField(
            model_name='salvo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvo', to='posts.post'),
        ),
        migrations.AddField(
            model_name='salvo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='curtida',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='un_post_user_curitda'),
        ),
        migrations.AddConstraint(
            model_name='salvo',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='un_post_user_salvo'),
        ),
    ]
